### ISSUE TITLE
Telegram Error in Log

### ISSUE THREAD

**Issue by aunrea** [MMRIZE/MMM-TelegramBot#28]
My mm-error.log is filling up with the following message, repeated thousands of time, making it almost impossible to open, nevermind read:

```
{ Error: ETELEGRAM: 409 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
    at request.then.resp (/home/pi/MagicMirror/modules/MMM-TelegramBot/node_modules/node-telegram-bot-api/src/telegram.js:213:15)
    at tryCatcher (/home/pi/MagicMirror/modules/MMM-TelegramBot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pi/MagicMirror/modules/MMM-TelegramBot/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/home/pi/MagicMirror/modules/MMM-TelegramBot/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/home/pi/MagicMirror/modules/MMM-TelegramBot/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/home/pi/MagicMirror/modules/MMM-TelegramBot/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/home/pi/MagicMirror/modules/MMM-TelegramBot/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/pi/MagicMirror/modules/MMM-TelegramBot/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/pi/MagicMirror/modules/MMM-TelegramBot/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/MagicMirror/modules/MMM-TelegramBot/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
  code: 'ETELEGRAM',
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: true,
        decoder: null,
        encoding: null },
     readable: false,
     _events:
      { end: [Array],
        close: [Array],
        data: [Function],
        error: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     socket:
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: null,
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: -1,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers:
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [TLSSocket],
        connection: [TLSSocket],
        _header:
        href:
         'https://api.telegram.org/bot932892623:AAGiUFq_U_vooXfI2ZWIbunk33Wl6Ta-zjc/getUpdates',
        req: [ClientRequest],
        ntick: true,
        response: [Circular],
        originalHost: 'api.telegram.org',
        originalHostHeaderName: 'host',
        responseContent: [Circular],
        _destdata: true,
        _ended: true,
        _callbackCalled: true },
     toJSON: [Function: responseToJSON],
     caseless: Caseless { dict: [Object] },
     body:
      { ok: false,
        error_code: 409,
        description:
         'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running' } } }
```

**Comment by eouia** [comment]
you probably be running more than one instance at once. stop other instances of MM.
